# Generated by Django 4.1 on 2022-08-04 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="salary",
        ),
        migrations.AddField(
            model_name="company",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="max_salary",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="min_salary",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
